import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import Link from 'next/link';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { AppBar, Toolbar, Button } from '@mui/material';
import theme from './theme';

export const workSans = Work_Sans({
  variable: '--font-work-sans',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <body className='font-default antialiased'>
          <ThemeProvider theme={theme}>
            <AppBar position='static'>
              <Toolbar>
                <div className='flex flex-grow gap-2'>
                  <Button color='inherit' component={Link} href='/'>
                    Home
                  </Button>
                  <Button color='inherit' component={Link} href='/profile'>
                    Profile
                  </Button>
                  <Button color='inherit' component={Link} href='/sign-in'>
                    Sign In
                  </Button>
                  <Button color='inherit' component={Link} href='/sign-up'>
                    Sign Up
                  </Button>
                  <Button
                    color='inherit'
                    component={Link}
                    href='/forgot-password'
                  >
                    Forgot Password
                  </Button>
                  <Button
                    color='inherit'
                    component={Link}
                    href='/reset-password'
                  >
                    Reset Password
                  </Button>
                </div>
              </Toolbar>
            </AppBar>
            {children}
          </ThemeProvider>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
